<?php

/****************************************************************

File:     /block/course_rollover/db/event.php

Purpose:  Message Event Handler

****************************************************************/

/* List of handlers that this block uses */
$handlers = array (
    'course_rollover_scheduled ' => array (
        'handlerfile'      => '/block/course_rollover/classlib.php',
        'handlerfunction'  => 'course_rollover::notification',
        'schedule'         => 'instant',
        'internal'         => 1,
   ),
	'course_rollover_commpleted ' => array (
       'handlerfile'      => '/block/course_rollover/classlib.php',
       'handlerfunction'  => 'course_rollover::notification',
       'schedule'         => 'cron',
       'internal'         => 1,
  )
);

/* List of events generated by the course_rollover block, with the fields on the event object.

course_rollover_scheduled
    ->component   = 'block_course_rollover';
    ->scheduledtime   = // The timestamp of when the rollover has been scheduled.
    ->userid      = // The user id that the course belongs to.
    ->courseid    = // The course id of the course the quiz belongs to.

course_rollover_commpleted
    ->component   = 'block_course_rollover';
    ->runtime  = // The timestamp of when the attempt was submitted.
    ->userid      = // The user id that the course belongs to.
    ->submitterid = // The user id of the user who sumitted the scheduled.
    ->courseid    = // The course id of the course the quiz belongs to.

*/

